<template>
  <div id="container">
    <SlideShow :images="getImages()">
      <img ref="im" src="/src/assets/tiledimage0.png"
           alt="A beautiful picture created by tiling together many minecraft blocks"/>
    </SlideShow>
    <div id="layer">

    </div>
  </div>
</template>

<script lang="ts">
import SlideShow from "@/components/SlideShow/SlideShow.vue";

export default {
  name: "HomeBanner",
  components: {SlideShow},
  methods: {
    getImages() {
      //https://wallpapercave.com/wp/wp2077533.jpg,
      return [
        {
          url: "/src/assets/tiledimage0.png",
          text: "Image generated by TiledImage project. Image made of many minecraft block textures. Original image from https://wallpapercave.com/wp/wp2077533.jpg"
        },
        {
          url: "/src/assets/onlinetictactoe.png",
          text: "OnlineTicTacToe Project. A Multiplayer TicTacToe"
        },
        {
          url: "/src/assets/bgario.png",
          text:"Python Bgario. an Agario inspired game created in python."
        },
        {
          url: "/src/assets/minesweeper.png",
          text:"Minesweeper. Created using css, html and javascript"
        }
      ]
    }
  }
}
</script>

<style scoped lang="sass">
@import "/src/assets/globals"
#container
  height: 100%
  width: 100%
  position: relative

  #layer
    width: 100%
    height: 100%

    background-color: rgba($color-dark2, 0.5)
    position: absolute
    left: 0
    top: 0
    pointer-events: none


</style>