<template>
  <div id="container">
    <SlideShow enable-overlay=true>
      <SlideshowItem v-for="image in getImages()"
                     :url="image.url"
                     :text="image.text"
      />
    </SlideShow>

    <div id="banner-title">
      <h1>ultr42</h1>
      <p>A cool site for my projects and other cool stuff</p>
    </div>
    <div id="scroll-link" title="Scroll down. There is more below" @click="scrolldowb()">
      <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">
        <path d="m18.707 12.707-1.414-1.414L13 15.586V6h-2v9.586l-4.293-4.293-1.414 1.414L12 19.414z"></path>
      </svg>
    </div>
  </div>

</template>

<script lang="ts">
import SlideShow from "@/components/SlideShow/SlideShow.vue";
import SlideshowItem from "@/components/SlideShow/SlideshowItem.vue";

export default {
  name: "HomeBanner",
  components: {SlideshowItem, SlideShow},
  methods: {
    scrolldowb(){
      window.location.replace("/#projects-view")
    },
    getImages() {
      //https://wallpapercave.com/wp/wp2077533.jpg,
      return [
        {
          url: "./tiledimage0.png",
          text: "Image generated by TiledImage project. Image made of many minecraft block textures. Original image from https://wallpapercave.com/wp/wp2077533.jpg"
        },
        {
          url: "./onlinetictactoe.png",
          text: "OnlineTicTacToe Project. A Multiplayer TicTacToe"
        },
        {
          url: "./bgario.png",
          text: "Python Bgario. an Agario inspired game created in python."
        },
        {
          url: "./minesweeper.png",
          text: "Minesweeper. Created using css, html and javascript"
        }
      ]
    }
  }
}
</script>

<style scoped lang="sass">
@import "/src/assets/globals"
#container
  height: calc(100vh - $size-7)
  width: 100vw
  position: relative

  #banner-title
    pointer-events: auto
    position: absolute
    width: fit-content
    height: fit-content
    margin: auto
    top: 0
    bottom: 0
    right: 0
    left: 0
    p
      color: $color-white2

  #scroll-link
    position: absolute
    width: fit-content
    height: fit-content
    top: 400px
    bottom: 0
    right: 0
    left: 0
    margin: auto
    display: flex
    flex-direction: column
    transition: transform 0.2s ease
    cursor: pointer
    svg
      fill: rgba($color-white2,0.6)

  #scroll-link:hover
    transform: translate(0,10px)


</style>