name: build-push-deploy
run-name: ${{ github.actor }} is building this app and pushing it to the builds branch
on:
  push:
    branches: [ "v8" ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write


concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:

  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Branch Name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      - name: Print Branch Name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install all dependencies
        run: npm ci

      # - name: Build (astro.js)
      #   uses: withastro/action@v5
      #   # with:
      #     # path: . # The root location of your Astro project inside the repository. (optional)
      #     # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
      #     # package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

      # - name: Push
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: builds # The branch name where you want to push the assets
      #     FOLDER: dist # The directory where your assets are generated
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
      #     MESSAGE: "Push: ({sha}) {msg} ${{ steps.extract_branch.outputs.branch }}" # The commit message
      #     TARGET_DIR: ${{ steps.extract_branch.outputs.branch }}
